sudo:   required
services:
        - docker
before_install:
        - docker build -t jagan2290/docker-react -f Dockerfile.dev .
script:
        - docker run jagan2290/docker-react npm run test -- --coverage
