sudo:   required
services:
        - docker
before_install:
        - docker build -t jagan2290/docker-react -f Dockerfile.dev .
script:
        - docker run -e CI=true jagan2290/docker-react npm run test
deploy:
        provider: elasticbeanstalk
        region: "us-east-1"
        app: "Docker-react"
        env: "DockerReact-env"
        bucket_name: "elasticbeanstalk-us-east-1-061992108729"
        bucket_path: "Docker-react"
        on:
                branch: master
        access_key_id: $AWS_ACCESS_KEY
        secret_access_key:
                secure: "$AWS_SECRET_KEY"
